import { AetherPalette } from "../../lib/types";
import { alpha } from "../../lib/utils";

export const getComponentColors = (p: AetherPalette) => {
  const mutedFg = alpha(p.core.fg, 65);

  return {
    // Base Colors
    foreground: p.core.fg,
    focusBorder: p.input.focusBorder,
    descriptionForeground: mutedFg,
    errorForeground: p.status.error,
    "icon.foreground": mutedFg,
    "widget.shadow": p.core.overlay,
    "selection.background": p.editor.selection,
    "sash.hoverBorder": p.tabs.activeBorderTop,
    "progressBar.background": p.tabs.activeBorderTop,
    "window.activeBorder": p.core.border,
    "window.inactiveBorder": alpha(p.core.border, 60),

    // Scrollbar
    "scrollbar.shadow": p.scrollBar.shadow,
    "scrollbarSlider.background": p.scrollBar.sliderBg,
    "scrollbarSlider.hoverBackground": p.scrollBar.sliderHover,
    "scrollbarSlider.activeBackground": p.scrollBar.sliderActive,

    // Tabs
    "editorGroupHeader.tabsBackground": alpha(p.titleBar.bg, 60),
    "editorGroupHeader.tabsBorder": p.tabs.border,
    "editorGroup.border": p.core.border,
    "tab.activeForeground": p.tabs.activeFg,
    "tab.border": p.tabs.border,
    "tab.activeBorderTop": p.tabs.activeBorderTop,
    "tab.activeBackground": alpha(p.tabs.activeBg, 75),
    "tab.inactiveBackground": alpha(p.tabs.inactiveBg, 60),
    "tab.inactiveForeground": p.tabs.inactiveFg,
    "tab.hoverBackground": alpha(p.tabs.activeBg, 50),
    "tab.hoverForeground": p.tabs.activeFg,

    // Buttons & Badges
    "button.background": p.button.primary.bg,
    "button.foreground": p.button.primary.fg,
    "button.hoverBackground": p.button.primary.hover,
    "button.secondaryBackground": p.button.secondary.bg,
    "button.secondaryForeground": p.button.secondary.fg,
    "button.secondaryHoverBackground": p.button.secondary.hover,
    "badge.foreground": p.activityBar.badgeFg,
    "badge.background": p.activityBar.badgeBg,

    // Inputs & Forms
    "input.background": p.input.bg,
    "input.border": p.input.border,
    "input.foreground": p.input.fg,
    "input.placeholderForeground": p.input.placeholder,
    "inputOption.activeBackground": alpha(p.input.focusBorder, 20),
    "inputOption.activeBorder": p.input.focusBorder,
    "inputOption.activeForeground": p.input.fg,
    "inputValidation.errorBackground": p.input.validation.errorBg,
    "inputValidation.errorForeground": p.input.fg,
    "inputValidation.errorBorder": p.input.validation.errorBorder,
    "dropdown.background": p.input.bg,
    "dropdown.foreground": p.input.fg,
    "dropdown.border": p.input.border,
    "dropdown.listBackground": p.input.bg,
    "checkbox.background": p.input.bg,
    "checkbox.foreground": p.input.fg,
    "checkbox.border": p.input.border,
    "checkbox.selectBackground": p.input.focusBorder,
    "checkbox.selectBorder": p.input.focusBorder,
    "radio.activeForeground": p.input.fg,
    "radio.activeBackground": alpha(p.input.focusBorder, 20),
    "radio.activeBorder": p.input.focusBorder,
    "radio.inactiveForeground": mutedFg,
    "radio.inactiveBackground": alpha(p.input.bg, 50),
    "radio.inactiveBorder": alpha(p.input.border, 50),

    // Lists & Trees
    "list.hoverBackground": p.list.hoverBg,
    "list.hoverForeground": p.core.fg,
    "list.activeSelectionBackground": p.list.activeSelectionBg,
    "list.activeSelectionForeground": p.list.activeSelectionFg,
    "list.inactiveSelectionBackground": p.list.inactiveSelectionBg,
    "list.inactiveSelectionForeground": p.core.fg,
    "list.focusBackground": p.list.focusBg,
    "list.focusForeground": p.core.fg,
    "list.dropBackground": alpha(p.list.activeSelectionBg, 40),
    "list.highlightForeground": p.editor.findMatch,
    "tree.indentGuidesStroke": alpha(p.core.fg, 15),
    "list.errorForeground": p.status.error,
    "list.warningForeground": p.status.warning,

    // Terminal
    "terminal.background": p.panel.bg,
    "terminal.foreground": p.core.fg,
    "terminal.border": p.panel.border,
    "terminalCursor.foreground": p.editor.cursor,
    "terminalCursor.background": p.editor.bg,
    "terminal.selectionBackground": p.editor.selection,
    "terminal.ansiBlack": p.terminal.black,
    "terminal.ansiRed": p.terminal.red,
    "terminal.ansiGreen": p.terminal.green,
    "terminal.ansiYellow": p.terminal.yellow,
    "terminal.ansiBlue": p.terminal.blue,
    "terminal.ansiMagenta": p.terminal.magenta,
    "terminal.ansiCyan": p.terminal.cyan,
    "terminal.ansiWhite": p.terminal.white,
    "terminal.ansiBrightBlack": p.terminal.brightBlack,
    "terminal.ansiBrightRed": p.terminal.brightRed,
    "terminal.ansiBrightGreen": p.terminal.brightGreen,
    "terminal.ansiBrightYellow": p.terminal.brightYellow,
    "terminal.ansiBrightBlue": p.terminal.brightBlue,
    "terminal.ansiBrightMagenta": p.terminal.brightMagenta,
    "terminal.ansiBrightCyan": p.terminal.brightCyan,
    "terminal.ansiBrightWhite": p.terminal.brightWhite,

    // Command Center & Menus
    "commandCenter.foreground": p.core.fg,
    "commandCenter.activeForeground": p.tabs.activeFg,
    "commandCenter.background": p.input.bg,
    "commandCenter.border": p.core.border,
    "commandCenter.activeBackground": alpha(p.input.bg, 80),
    "menu.background": p.input.bg,
    "menu.foreground": p.core.fg,
    "menu.border": p.core.border,
    "menu.selectionBackground": p.list.activeSelectionBg,
    "menu.selectionForeground": p.list.activeSelectionFg,
    "menu.separatorBackground": p.core.border,

    // Widgets & Extras
    "editorWidget.background": p.input.bg,
    "editorWidget.foreground": p.input.fg,
    "editorWidget.border": p.input.border,
    "editorSuggestWidget.background": p.input.bg,
    "editorSuggestWidget.foreground": p.input.fg,
    "editorSuggestWidget.border": p.input.border,
    "editorSuggestWidget.selectedBackground": p.list.activeSelectionBg,
    "editorSuggestWidget.highlightForeground": p.editor.findMatch,
    "quickInput.background": p.input.bg,
    "quickInput.foreground": p.input.fg,
    "quickInputList.focusBackground": p.list.activeSelectionBg,
    "quickInputList.focusForeground": p.list.activeSelectionFg,
    "keybindingLabel.background": p.input.bg,
    "keybindingLabel.foreground": p.core.fg,
    "keybindingLabel.border": p.core.border,
    "keybindingLabel.bottomBorder": p.core.border,
    "notifications.background": p.input.bg,
    "notifications.foreground": p.core.fg,
    "notificationToast.border": p.core.border,
    "textBlockQuote.background": alpha(p.sideBar.bg, 50),
    "textBlockQuote.border": p.tabs.activeBorderTop,
    "textCodeBlock.background": p.input.bg,
    "textLink.activeForeground": p.button.primary.hover,
    "textLink.foreground": p.button.primary.bg,
    "toolbar.hoverBackground": alpha(p.core.fg, 10),

    // Icons & Git
    "symbolIcon.classForeground": p.syntax.classes,
    "symbolIcon.constructorForeground": p.syntax.functions,
    "symbolIcon.enumeratorForeground": p.syntax.types,
    "symbolIcon.fieldForeground": p.syntax.variables,
    "symbolIcon.functionForeground": p.syntax.functions,
    "symbolIcon.interfaceForeground": p.syntax.types,
    "symbolIcon.methodForeground": p.syntax.functions,
    "symbolIcon.variableForeground": p.syntax.variables,
    "symbolIcon.constantForeground": p.syntax.constants,
    "symbolIcon.stringForeground": p.syntax.strings,
    "symbolIcon.keywordForeground": p.syntax.keywords,
    "symbolIcon.numberForeground": p.syntax.numbers,
    "symbolIcon.booleanForeground": p.syntax.constants,
    "symbolIcon.arrayForeground": p.syntax.types,
    "symbolIcon.operatorForeground": p.syntax.operators,
    "debugIcon.breakpointForeground": p.status.error,
    "debugIcon.startForeground": p.status.success,
    "debugIcon.pauseForeground": p.status.warning,
    "debugIcon.stopForeground": p.status.error,
    "debugToolBar.background": p.panel.bg,
    "gitDecoration.addedResourceForeground": p.git.added,
    "gitDecoration.modifiedResourceForeground": p.git.modified,
    "gitDecoration.deletedResourceForeground": p.git.deleted,
    "gitDecoration.conflictingResourceForeground": p.git.conflict,
    "gitDecoration.ignoredResourceForeground": p.git.ignored,
    "editorError.foreground": p.status.error,
    "editorWarning.foreground": p.status.warning,
    "editorInfo.foreground": p.status.info,
  };
};
